name: 'CI: Detect New Packages on Master'

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  detect-new-packages:
    name: Check for new unpublished packages
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js
        uses: ./.github/actions/setup-nodejs
        with:
          build-command: ''
          install-command: pnpm install --frozen-lockfile --dir ./.github/scripts --ignore-workspace

      - name: Check for new unpublished packages
        id: detect
        continue-on-error: true
        run: node .github/scripts/detect-new-packages.mjs
