name: 'Util: Approve and set Automerge'

run-name: Approve and automerge PR ${{ inputs.pull-request-number }}

on:
  workflow_call:
    inputs:
      pull-request-number:
        type: string
        required: true

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  approve-and-automerge:
    if: |
      inputs.pull-request-number != ''
    runs-on: ubuntu-slim
    environment: release
    steps:
      - name: Fetch secrets from Infisical
        uses: Infisical/secrets-action@v1.0.15
        with:
          method: oidc
          identity-id: 436a2630-fad8-475b-8f00-5ab158e9919e
          project-slug: project-nd-zj
          env-slug: dev
          secret-path: /n8n

      # - name: Approve PR (as the App)
      #   env:
      #     GH_TOKEN: ${{ env.GITHUB_TOKEN }}
      #   run: |
      #     gh pr review "${{ inputs.pull-request-number }}" \
      #       --approve \
      #       --repo "${{ github.repository }}"

      - name: Enable auto-merge (merge when checks pass)
        env:
          GH_TOKEN: ${{ env.GITHUB_TOKEN }}
        run: |
          gh pr merge "${{ inputs.pull-request-number }}" \
            --auto \
            --squash \
            --repo "${{ github.repository }}"
